'use client'

import { useState } from 'react'
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, Bell, BookOpen, Boxes, CalendarDays, CheckCircle2, ChevronDown, CircleHelp, ClipboardList, Clock3, FileText, Filter, LayoutDashboard, Menu, MoreHorizontal, PackageCheck, Plus, Search, Settings, Ship, Truck, Users, X } from 'lucide-react'

const navItems = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Quotations', icon: FileText, count: '12' }, { label: 'Shipments & Jobs', icon: Ship, count: '28' }, { label: 'Documents', icon: BookOpen, count: '6' }, { label: 'Tasks & Exceptions', icon: ClipboardList, count: '4' },
]
const quotes = [
  ['QT-2481', 'Meridian Retail Group', 'Lagos → Rotterdam', 'Ocean FCL', '$18,420', 'Awaiting response', 'amber'], ['QT-2480', 'Atlas Manufacturing', 'Shanghai → Felixstowe', 'Ocean LCL', '$9,850', 'Draft', 'slate'], ['QT-2479', 'Northstar Foods', 'Accra → London', 'Air Freight', '$4,260', 'Approved', 'emerald'], ['QT-2478', 'Greenline Energy', 'Houston → Tema', 'Project Cargo', '$32,100', 'In review', 'blue'],
]
const shipments = [
  ['FML-10482', 'Meridian Retail Group', 'Lagos → Rotterdam', 'Vessel departed', 68, '18 Oct 2026', 'On track', 'emerald'], ['FML-10481', 'Atlas Manufacturing', 'Shanghai → Felixstowe', 'Awaiting customs docs', 42, '22 Oct 2026', 'At risk', 'amber'], ['FML-10479', 'Northstar Foods', 'Accra → London', 'Delivered', 100, 'Delivered 04 Oct', 'Complete', 'slate'],
]
function Badge({ children, tone }: { children: React.ReactNode; tone: string }) { return <span className={`status-badge ${tone}`}><span className="status-dot" />{children}</span> }
function Stat({ label, value, change, icon: Icon, down = false }: { label: string; value: string; change: string; icon: typeof Clock3; down?: boolean }) { return <div className="stat-card"><div className="stat-top"><span className="stat-label">{label}</span><span className="icon-box"><Icon /></span></div><div className="stat-value">{value}</div><div className="stat-foot"><span className={down ? 'negative' : 'positive'}>{down ? <ArrowDownRight /> : <ArrowUpRight />}{change}</span><span>vs last month</span></div></div> }
function Header({ title, subtitle, action, onAction }: { title: string; subtitle: string; action?: string; onAction?: () => void }) { return <div className="page-heading"><div><p className="eyebrow">Monday, 5 October 2026</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><div className="heading-actions"><button className="button secondary"><Filter /> Filters</button>{action && <button className="button primary" onClick={onAction}><Plus /> {action}</button>}</div></div> }
function Panel({ title, subtitle, children, action = 'View all' }: { title: string; subtitle?: string; children: React.ReactNode; action?: string }) { return <section className="panel"><div className="panel-header"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action && <button className="text-button">{action} <ArrowUpRight /></button>}</div>{children}</section> }
function Table({ type }: { type: 'quotes' | 'shipments' | 'documents' | 'tasks' }) { if (type === 'quotes') return <div className="table-wrap"><table><thead><tr><th>QUOTE</th><th>CUSTOMER</th><th>LANE & MODE</th><th>VALUE</th><th>STATUS</th><th>AGE</th></tr></thead><tbody>{quotes.map(q => <tr key={q[0]}><td><strong className="mono">{q[0]}</strong></td><td><strong>{q[1]}</strong></td><td><span>{q[2]}</span><small>{q[3]}</small></td><td><strong>{q[4]}</strong></td><td><Badge tone={q[6]}>{q[5]}</Badge></td><td className="muted">2h ago</td></tr>)}</tbody></table></div>
  if (type === 'shipments') return <div className="table-wrap"><table><thead><tr><th>JOB</th><th>CUSTOMER</th><th>ROUTE</th><th>MILESTONE</th><th>ETA</th><th>STATUS</th></tr></thead><tbody>{shipments.map(s => <tr key={s[0]}><td><strong className="mono">{s[0]}</strong></td><td><strong>{s[1]}</strong></td><td>{s[2]}</td><td>{s[3]}</td><td><strong>{s[5]}</strong></td><td><Badge tone={s[7]}>{s[6]}</Badge></td></tr>)}</tbody></table></div>
  const rows = type === 'documents' ? [['Commercial invoice', 'FML-10481', 'Atlas Manufacturing', 'Awaiting upload', 'amber'], ['Bill of lading', 'FML-10482', 'Meridian Retail Group', 'Verified', 'emerald'], ['Packing list', 'FML-10479', 'Northstar Foods', 'Verified', 'emerald'], ['Certificate of origin', 'FML-10477', 'Greenline Energy', 'Needs review', 'blue']] : [['Upload customs documents', 'FML-10481', 'Ama Mensah', 'Due today', 'amber'], ['Confirm vessel arrival', 'FML-10482', 'Kojo Asante', 'In progress', 'blue'], ['Review carrier invoice', 'FML-10477', 'Kemi Oladipo', 'Open', 'slate'], ['Update customer ETA', 'FML-10479', 'Ama Mensah', 'Complete', 'emerald']]
  return <div className="table-wrap"><table><thead><tr><th>{type === 'documents' ? 'DOCUMENT' : 'TASK'}</th><th>JOB</th><th>OWNER</th><th>STATUS</th></tr></thead><tbody>{rows.map(r => <tr key={r[0]}><td><strong>{r[0]}</strong></td><td className="mono">{r[1]}</td><td>{r[2]}</td><td><Badge tone={r[4]}>{r[3]}</Badge></td></tr>)}</tbody></table></div> }
function Overview({ setActiveNav }: { setActiveNav: (x: string) => void }) { return <><Header title="Good morning, Kemi" subtitle="Here’s what’s happening across your operations today." action="New quotation" onAction={() => setActiveNav('Quotations')} /><section className="stats-grid"><Stat label="Open quotations" value="24" change="12.5%" icon={FileText} /><Stat label="Active shipments" value="86" change="8.2%" icon={Ship} /><Stat label="Avg. turnaround" value="18.4h" change="4.1%" icon={Clock3} down /><Stat label="Exceptions" value="07" change="2 new" icon={AlertTriangle} down /></section><div className="section-grid"><Panel title="Quotation pipeline" subtitle="Track your most recent opportunities"><div className="pipeline"><div><strong>24</strong><span>Total open</span></div><div><strong className="amber-text">12</strong><span>Awaiting response</span></div><div><strong className="blue-text">07</strong><span>In review</span></div><div><strong className="green-text">05</strong><span>Approved</span></div></div><Table type="quotes" /></Panel><Panel title="Activity" subtitle="Latest updates from your team" action=""><div className="activity-list"><div className="activity-item"><div className="activity-icon green"><CheckCircle2 /></div><div><p><strong>Ama Mensah</strong> marked <strong>FML-10479</strong> as delivered</p><span>12 minutes ago</span></div></div><div className="activity-item"><div className="activity-icon amber"><AlertTriangle /></div><div><p><strong>Customs documentation</strong> is missing for FML-10481</p><span>48 minutes ago</span></div></div><div className="activity-item"><div className="activity-icon blue"><FileText /></div><div><p><strong>Kojo Asante</strong> created quotation <strong>QT-2481</strong></p><span>2 hours ago</span></div></div></div><button className="activity-footer">View all activity <ArrowUpRight /></button></Panel></div><Panel title="Shipment operations" subtitle="Live view of your active jobs and milestones"><Table type="shipments" /></Panel></> }
function Module({ activeNav, setActiveNav }: { activeNav: string; setActiveNav: (x: string) => void }) { if (activeNav === 'Overview') return <Overview setActiveNav={setActiveNav} />; const config: Record<string, [string, string, string, 'quotes' | 'shipments' | 'documents' | 'tasks']> = { Quotations: ['Quotation workspace', 'Create, track, and convert freight opportunities into jobs.', 'New quotation', 'quotes'], 'Shipments & Jobs': ['Shipments & jobs', 'Monitor live freight movements, milestones, and customer commitments.', 'Create shipment', 'shipments'], Documents: ['Central documentation', 'Keep every shipment document verified, visible, and ready for handoff.', 'Upload document', 'documents'], 'Tasks & Exceptions': ['Tasks & exceptions', 'Resolve operational blockers before they impact customers.', 'Create task', 'tasks'], Performance: ['Performance insights', 'Turnaround times, win rates, and operational health at a glance.', 'Export report', 'shipments'], Calendar: ['Operations calendar', 'Plan milestones, handoffs, and customer updates across the week.', 'Add milestone', 'tasks'], Settings: ['Workspace settings', 'Manage roles, notifications, templates, and operational preferences.', 'Save changes', 'tasks'] }; const c = config[activeNav] || config.Quotations; return <><Header title={c[0]} subtitle={c[1]} action={c[2]} /><section className="stats-grid"><Stat label="Open items" value={activeNav === 'Shipments & Jobs' ? '86' : activeNav === 'Documents' ? '42' : '24'} change="12.5%" icon={activeNav === 'Documents' ? BookOpen : activeNav === 'Tasks & Exceptions' ? ClipboardList : FileText} /><Stat label="Needs attention" value="07" change="2 new" icon={AlertTriangle} down /><Stat label="Completed this month" value="128" change="18.4%" icon={CheckCircle2} /><Stat label="Avg. turnaround" value="18.4h" change="4.1%" icon={Clock3} down /></section><Panel title={activeNav === 'Performance' ? 'Operational performance' : activeNav === 'Calendar' ? 'Upcoming operational activity' : 'Work queue'} subtitle="Updated just now"><Table type={c[3]} /></Panel></> }
export default function Page() { const [activeNav, setActiveNav] = useState('Overview'); const [mobileNav, setMobileNav] = useState(false); return <div className="app-shell"><aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Boxes /></div><div><strong>FAME<span>LOGISTICS</span></strong><small>OPERATIONS PLATFORM</small></div><button className="close-mobile" onClick={() => setMobileNav(false)} aria-label="Close menu"><X /></button></div><div className="workspace"><div className="workspace-avatar">FM</div><div><strong>Fame Logistics</strong><span>Operations workspace</span></div><ChevronDown /></div><nav className="main-nav" aria-label="Main navigation"><p className="nav-caption">WORKSPACE</p>{navItems.map(({ label, icon: Icon, count }) => <button key={label} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => { setActiveNav(label); setMobileNav(false) }}><Icon /><span>{label}</span>{count && <em>{count}</em>}</button>)}<p className="nav-caption">INSIGHTS</p>{[['Performance', BarChart3], ['Calendar', CalendarDays]].map(([label, Icon]) => <button key={label as string} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setActiveNav(label as string)}><Icon /><span>{label as string}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><CircleHelp /><span>Help center</span></button><button className={`nav-item ${activeNav === 'Settings' ? 'active' : ''}`} onClick={() => setActiveNav('Settings')}><Settings /><span>Settings</span></button><div className="profile"><div className="profile-avatar">KO</div><div><strong>Kemi Oladipo</strong><span>Operations lead</span></div><MoreHorizontal /></div></div></aside><main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open menu"><Menu /></button><div className="breadcrumbs"><span>Workspace</span><b>/</b><strong>{activeNav}</strong></div><div className="top-actions"><div className="search"><Search /><input placeholder="Search shipments, quotes..." aria-label="Search" /><kbd>⌘ K</kbd></div><button className="icon-button notification" aria-label="Notifications"><Bell /><i /></button><button className="avatar-button">KO</button></div></header><div className="content-wrap"><Module activeNav={activeNav} setActiveNav={setActiveNav} /></div></main></div> }
